services:
  - type: web
    name: my-e-shop
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DATABASE_URL
        value: postgres://user:password@hostname:port/dbname
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: ALLOWED_HOSTS
        value: .render.com, .yourdomain.com
